### ISSUE TITLE
graphic 툴이 멋져서 왔습니다. 

### ISSUE THREAD

**Issue by easylogic** [diayoak/Graphic-Tool#1]
혹시 계속 진행을 안하시나요?  

툴이 상당히 깔끔해서 하나의 영역을 잘 다루시면 좋을 것 같아요.

**Comment by diayoak** [comment]
감사합니다.

예전에 학생일 때, 작업한 프로젝트라서 완성도가 높지 않은데 칭찬해 주시니 기분이 좋네요.
작업은 최근에 여유가 생겨서 다시 진행할 예정에 있습니다.

**Comment by easylogic** [comment]
우와 다시 시작하시면 정말 멋진 툴이  될 것 같습니다.   ^^
